# Generated by Django 6.1 on 2026-08-30 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('pais_origem', models.CharField(blank=True, max_length=80)),
                ('site', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('CPU', 'Processador (CPU)'), ('GPU', 'Placa de Vídeo (GPU)'), ('RAM', 'Memória RAM'), ('SSD', 'Armazenamento SSD'), ('HD', 'Armazenamento HD'), ('MOBO', 'Placa-mãe'), ('PSU', 'Fonte de Alimentação'), ('CASE', 'Gabinete')], max_length=4)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('especificacoes', models.TextField(blank=True)),
                ('em_estoque', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='app.fabricante')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
